"""Schemas package initialization."""
from app.schemas.auth import (
    PhysicianRegister,
    PhysicianLogin,
    TokenResponse,
    PatientSessionStart,
    PatientSessionResponse,
    PhysicianResponse,
)
from app.schemas.languages import (
    Language,
    LanguageCapabilities,
    LanguageListResponse,
    LANGUAGE_REGISTRY,
    get_language_by_code,
    get_supported_languages,
)
from app.schemas.clinical_history import (
    Provenance,
    ClinicalFact,
    SurgicalHistoryEntry,
    MedicationEntry,
    AllergyEntry,
    ClinicalHistoryData,
    DraftAnswerUpdate,
    ClinicalHistoryUpdate,
    ClinicalHistoryResponse,
    TouchAnswerSubmit,
    SeverityUpdate,
)
from app.schemas.conversation import (
    Question,
    QuestionOption,
    QuestionnaireSchema,
    ConversationStartRequest,
    ConversationStartResponse,
    ConversationResponse,
    NextQuestionResponse,
    ConversationState,
    TranscriptConfirmRequest,
)
from app.schemas.tts import TTSRequest, TTSResponse
from app.schemas.ayush import (
    AyushAnswer,
    PrakritiScore,
    AgniAssessment,
    KoshthaAssessment,
    AharaViharaProfile,
    SatvaAssessment,
    AyushProfile,
    AyushQuestionRequest,
    AyushQuestionResponse,
    AyushAnswerSubmit,
    AyushProfileResponse,
    AyushIndicator,
)
from app.schemas.ocr import (
    MedicationExtraction,
    LabExtraction,
    DiagnosisExtraction,
    DocumentDates,
    StructuredEntities,
    OCRUploadResponse,
    OCRProcessingResult,
    OCRDocumentListResponse,
    OCRDocumentDetailResponse,
)
from app.schemas.queue import (
    QueueTokenCreate,
    QueueTokenUpdate,
    QueueTokenResponse,
    QueueListResponse,
)
from app.schemas.fhir import (
    FHIRPatient,
    FHIREncounter,
    FHIRCondition,
    FHIRObservation,
    FHIRMedicationStatement,
    FHIRAllergyIntolerance,
    FHIRComposition,
    FHIRBundle,
    FHIRBundleResponse,
)

__all__ = [
    # Auth
    "PhysicianRegister",
    "PhysicianLogin",
    "TokenResponse",
    "PatientSessionStart",
    "PatientSessionResponse",
    "PhysicianResponse",
    # Languages
    "Language",
    "LanguageCapabilities",
    "LanguageListResponse",
    "LANGUAGE_REGISTRY",
    "get_language_by_code",
    "get_supported_languages",
    # Clinical History
    "Provenance",
    "ClinicalFact",
    "SurgicalHistoryEntry",
    "MedicationEntry",
    "AllergyEntry",
    "ClinicalHistoryData",
    "DraftAnswerUpdate",
    "ClinicalHistoryUpdate",
    "ClinicalHistoryResponse",
    "TouchAnswerSubmit",
    "SeverityUpdate",
    # Conversation
    "Question",
    "QuestionOption",
    "QuestionnaireSchema",
    "ConversationStartRequest",
    "ConversationStartResponse",
    "ConversationResponse",
    "NextQuestionResponse",
    "ConversationState",
    "TranscriptConfirmRequest",
    # TTS
    "TTSRequest",
    "TTSResponse",
    # AYUSH
    "AyushAnswer",
    "PrakritiScore",
    "AgniAssessment",
    "KoshthaAssessment",
    "AharaViharaProfile",
    "SatvaAssessment",
    "AyushProfile",
    "AyushQuestionRequest",
    "AyushQuestionResponse",
    "AyushAnswerSubmit",
    "AyushProfileResponse",
    "AyushIndicator",
    # OCR
    "MedicationExtraction",
    "LabExtraction",
    "DiagnosisExtraction",
    "DocumentDates",
    "StructuredEntities",
    "OCRUploadResponse",
    "OCRProcessingResult",
    "OCRDocumentListResponse",
    "OCRDocumentDetailResponse",
    # Queue
    "QueueTokenCreate",
    "QueueTokenUpdate",
    "QueueTokenResponse",
    "QueueListResponse",
    # FHIR
    "FHIRPatient",
    "FHIREncounter",
    "FHIRCondition",
    "FHIRObservation",
    "FHIRMedicationStatement",
    "FHIRAllergyIntolerance",
    "FHIRComposition",
    "FHIRBundle",
    "FHIRBundleResponse",
]
